name: "my github action demo"

on:
    push:
        branches: [main]


jobs:
    run:
        name: "run"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-go@v3
              with:
                go-version: '1.19' # The Go version to download (if necessary) and use.
            - 
              name: "步骤-启动go项目1"
              env:
                GO111MODULE: "on"
              run: | #可以执行多行linux命令
                go mod tidy 
                go build -o main main.go 
                ./main &
                curl localhost:8080/
